[project]
name = "oddwinefixes"
version = "0.1.0"
description = "A PE Analyser and Wine/Proton missing dependency/font fixer"
readme = "README.md"
authors = [
    { name = "Odd Østlie", email = "oddostlie@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [ "pefile" ]

[project.scripts]
oddwinefixes = "oddwinefixes:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
